version: '3'

services:
  nodeapp:
   image: justinmoon/loadbalancer-node
   ports:
     - 5000:5000
   deploy:
     replicas: 15
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  proxy:
    image: justinmoon/loadbalancer-nginx
    ports:
      - 80:7777
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay
